name: cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  bloc_test: ^9.1.0
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  
